services:
  _defaults:
    autowire: true

  _instanceof:
    HeimrichHannot\ContaoExporterBundle\Exporter\ExporterInterface:
      tags: ['huh_exporter.exporter']
      lazy: true

  HeimrichHannot\ContaoExporterBundle\:
    resource: '../../{Command,Migration}/*'
    autoconfigure: true

  HeimrichHannot\ContaoExporterBundle\EventListener\Contao\:
    resource: '../../EventListener/Contao/*'
    autoconfigure: true

  HeimrichHannot\ContaoExporterBundle\Manager\ExporterOperationManager:
    arguments:
      - !tagged_iterator huh.exporter.operation

# Manager

  huh.exporter.manager.exporter:
    class: HeimrichHannot\ContaoExporterBundle\Manager\ExporterManager
    public: true
  HeimrichHannot\ContaoExporterBundle\Manager\ExporterManager: '@huh.exporter.manager.exporter'

# Listener

  huh.exporter.listener.dc.exporter:
    class: HeimrichHannot\ContaoExporterBundle\EventListener\DataContainer\ExporterListener
    public: true
  huh.exporter.listener.dc.module:
    class: HeimrichHannot\ContaoExporterBundle\EventListener\DataContainer\ModuleListener
    public: true

# Actions

  huh.exporter.action.export:
    class: HeimrichHannot\ContaoExporterBundle\Action\ExportAction
    public: true
  HeimrichHannot\ContaoExporterBundle\Action\ExportAction: "@huh.exporter.action.export"

  huh.exporter.action.backendexport:
    class: HeimrichHannot\ContaoExporterBundle\Action\BackendExportAction
    public: true
  HeimrichHannot\ContaoExporterBundle\Action\BackendExportAction: "@huh.exporter.action.backendexport"

  huh.exporter.action.frontendexport:
    class: HeimrichHannot\ContaoExporterBundle\Action\FrontendExportAction
    public: true

# Exporter

  HeimrichHannot\ContaoExporterBundle\Exporter\Concrete\CsvExporter: ~
  HeimrichHannot\ContaoExporterBundle\Exporter\Concrete\ExcelExporter: ~
  HeimrichHannot\ContaoExporterBundle\Exporter\Concrete\PdfExporter: ~
  HeimrichHannot\ContaoExporterBundle\Exporter\Concrete\MediaExporter: ~
